[pytest]
testpaths = tests
norecursedirs =
    tests/test_files
addopts = -q --cov=pptx --cov-report=term-missing --cov-fail-under=60
python_files = test_*.py
python_functions = test_*
python_classes = Test*
