# -*- coding: utf-8 -*-
#
# python-pptx documentation build configuration file, created by
# sphinx-quickstart on Thu Nov 29 13:59:35 2012.
#
# This file is execfile()d with the current directory set to its containing
# dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath(".."))

from pptx import __version__  # noqa: E402


# -- General configuration --------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
]

# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = u"python-pptx"
copyright = u"2012, 2013, Steve Canny"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# A string of reStructuredText that will be included at the end of every source
# file that is read. This is the right place to add substitutions that should
# be available in every file.
rst_epilog = """
.. |ActionSetting| replace:: :class:`.ActionSetting`

.. |Adjustment| replace:: :class:`.Adjustment`

.. |AnimationEffect| replace:: :class:`.AnimationEffect`

.. |AnimationEffectView| replace:: :class:`.AnimationEffectView`

.. |AdjustmentCollection| replace:: :class:`.AdjustmentCollection`

.. |AreaSeries| replace:: :class:`.AreaSeries`

.. |AttributeError| replace:: :exc:`.AttributeError`

.. |Audio| replace:: :class:`.Audio`

.. |Axis| replace:: :class:`.Axis`

.. |AxisTitle| replace:: :class:`.AxisTitle`

.. |_Background| replace:: :class:`._Background`

.. |_EffectiveBackground| replace:: :class:`._EffectiveBackground`

.. |BarPlot| replace:: :class:`.BarPlot`

.. |BarSeries| replace:: :class:`.BarSeries`

.. |BaseFileSystem| replace:: :class:`BaseFileSystem`

.. |_BaseMaster| replace:: :class:`._BaseMaster`

.. |BasePlaceholder| replace:: :class:`.BasePlaceholder`

.. |_BasePlot| replace:: :class:`._BasePlot`

.. |BaseShape| replace:: :class:`.BaseShape`

.. |BaseSlidePart| replace:: :class:`.BaseSlidePart`

.. |BubbleChartData| replace:: :class:`.BubbleChartData`

.. |_BulletFormat| replace:: :class:`._BulletFormat`

.. |bool| replace:: :class:`bool`

.. |BubblePlot| replace:: :class:`.BubblePlot`

.. |BubblePoints| replace:: :class:`.BubblePoints`

.. |BubbleSeries| replace:: :class:`.BubbleSeries`

.. |BubbleSeriesData| replace:: :class:`.BubbleSeriesData`

.. |category.Categories| replace:: :class:`~.category.Categories`

.. |data.Categories| replace:: :class:`~.data.Categories`

.. |category.Category| replace:: :class:`~.category.Category`

.. |data.Category| replace:: :class:`~.data.Category`

.. |CategoryAxis| replace:: :class:`.CategoryAxis`

.. |CategoryChartData| replace:: :class:`.CategoryChartData`

.. |CategoryLevel| replace:: :class:`.CategoryLevel`

.. |CategoryPoints| replace:: :class:`.CategoryPoints`

.. |_Cell| replace:: :class:`_Cell`

.. |Chart| replace:: :class:`.Chart`

.. |ChartData| replace:: :class:`.ChartData`

.. |ChartDrawingPart| replace:: :class:`.ChartDrawingPart`

.. |ChartFormat| replace:: :class:`.ChartFormat`

.. |ChartPart| replace:: :class:`.ChartPart`

.. |ChartTitle| replace:: :class:`.ChartTitle`

.. |ChartXmlWriter| replace:: :class:`.ChartXmlWriter`

.. |_Close| replace:: :class:`_Close`

.. |Collection| replace:: :class:`Collection`

.. |ColorFormat| replace:: :class:`.ColorFormat`

.. |_Column| replace:: :class:`_Column`

.. |_ColumnCollection| replace:: :class:`_ColumnCollection`

.. |Comment| replace:: :class:`.Comment`

.. |CommentAuthor| replace:: :class:`.CommentAuthor`

.. |CommentAuthors| replace:: :class:`.CommentAuthors`

.. |Comments| replace:: :class:`.Comments`

.. |Connector| replace:: :class:`.Connector`

.. |ConnectorAdjustmentCollection| replace:: :class:`.ConnectorAdjustmentCollection`

.. |CoreProperties| replace:: :class:`.CoreProperties`

.. |CustomProperties| replace:: :class:`.CustomProperties`

.. |DataLabel| replace:: :class:`.DataLabel`

.. |_DataTable| replace:: :class:`~pptx.chart.chart._DataTable`

.. |DataLabels| replace:: :class:`.DataLabels`

.. |DateAxis| replace:: :class:`.DateAxis`

.. |datetime| replace:: :class:`datetime.datetime`

.. |DirectoryFileSystem| replace:: :class:`DirectoryFileSystem`

.. |DrawingOperations| replace:: :class:`.DrawingOperations`

.. |Emu| replace:: :class:`.Emu`

.. |ErrorBars| replace:: :class:`.ErrorBars`

.. |ExtendedPropertiesPart| replace:: :class:`.ExtendedPropertiesPart`

.. |False| replace:: :class:`False`

.. |_Field| replace:: :class:`._Field`

.. |FileSystem| replace:: :class:`FileSystem`

.. |FillFormat| replace:: :class:`.FillFormat`

.. |float| replace:: :class:`float`

.. |Font| replace:: :class:`.Font`

.. |FreeformBuilder| replace:: :class:`.FreeformBuilder`

.. |GradientStops| replace:: :class:`.GradientStops`

.. |GraphicFrame| replace:: :class:`.GraphicFrame`

.. |GroupShape| replace:: :class:`.GroupShape`

.. |GroupShapes| replace:: :class:`.GroupShapes`

.. |_HeaderFooter| replace:: :class:`._HeaderFooter`

.. |_Hyperlink| replace:: :class:`._Hyperlink`

.. |Hyperlink| replace:: :class:`.Hyperlink`

.. |Image| replace:: :class:`.Image`

.. |ImagePart| replace:: :class:`.ImagePart`

.. |Inches| replace:: :class:`.Inches`

.. |int| replace:: :class:`int`

.. |InvalidXmlError| replace:: :exc:`InvalidXmlError`

.. |KeyError| replace:: :exc:`KeyError`

.. |LayoutPlaceholder| replace:: :class:`.LayoutPlaceholder`

.. |LayoutPlaceholders| replace:: :class:`.LayoutPlaceholders`

.. |LayoutShapes| replace:: :class:`.LayoutShapes`

.. |Legend| replace:: :class:`.Legend`

.. |Length| replace:: :class:`.Length`

.. |LineEndFormat| replace:: :class:`.LineEndFormat`

.. |LineFormat| replace:: :class:`.LineFormat`

.. |LinePlot| replace:: :class:`.LinePlot`

.. |_LineSegment| replace:: :class:`._LineSegment`

.. |LineSeries| replace:: :class:`.LineSeries`

.. |list| replace:: :class:`list`

.. |MajorGridlines| replace:: :class:`.MajorGridlines`

.. |ManualLayout| replace:: :class:`~pptx.chart.datalabel.ManualLayout`

.. |Marker| replace:: :class:`.Marker`

.. |MinorGridlines| replace:: :class:`.MinorGridlines`

.. |MasterPlaceholder| replace:: :class:`.MasterPlaceholder`

.. |MasterPlaceholders| replace:: :class:`.MasterPlaceholders`

.. |MasterShapes| replace:: :class:`.MasterShapes`

.. |_MediaFormat| replace:: :class:`._MediaFormat`

.. |MediaPart| replace:: :class:`.MediaPart`

.. |Movie| replace:: :class:`.Movie`

.. |None| replace:: :class:`None`

.. |NotesMaster| replace:: :class:`.NotesMaster`

.. |NotesSlide| replace:: :class:`.NotesSlide`

.. |NotesSlidePlaceholders| replace:: :class:`.NotesSlidePlaceholders`

.. |NotesSlideShapes| replace:: :class:`.NotesSlideShapes`

.. |NotImplementedError| replace:: :exc:`NotImplementedError`

.. |OpcPackage| replace:: :class:`.OpcPackage`

.. |Package| replace:: :class:`Package`

.. |PackURI| replace:: :class:`.PackURI`

.. |_Paragraph| replace:: :class:`_Paragraph`

.. |Part| replace:: :class:`Part`

.. |PartTypeSpec| replace:: :class:`PartTypeSpec`

.. |Path| replace:: :class:`.Path`

.. |PathGeometry| replace:: :class:`.PathGeometry`

.. |Picture| replace:: :class:`.Picture`

.. |PieSeries| replace:: :class:`.PieSeries`

.. |PiePlot| replace:: :class:`~pptx.chart.plot.PiePlot`

.. |Pie3DPlot| replace:: :class:`~pptx.chart.plot.Pie3DPlot`

.. |_PlaceholderFormat| replace:: :class:`._PlaceholderFormat`

.. |PlaceholderGraphicFrame| replace:: :class:`.PlaceholderGraphicFrame`

.. |PlaceholderPicture| replace:: :class:`.PlaceholderPicture`

.. |PlotArea| replace:: :class:`.PlotArea`

.. |Plots| replace:: :class:`.Plots`

.. |Point| replace:: :class:`.Point`

.. |pp| replace:: `python-pptx`

.. |Presentation| replace:: :class:`~pptx.presentation.Presentation`

.. |PresentationPart| replace:: :class:`.PresentationPart`

.. |PROG_ID| replace:: :class:`~pptx.enum.shapes.PROG_ID`

.. |Pt| replace:: :class:`.Pt`

.. |RadarSeries| replace:: :class:`.RadarSeries`

.. |_Relationship| replace:: :class:`._Relationship`

.. |_Relationships| replace:: :class:`_Relationships`

.. |RGBColor| replace:: :class:`.RGBColor`

.. |_Row| replace:: :class:`_Row`

.. |_RowCollection| replace:: :class:`_RowCollection`

.. |_Run| replace:: :class:`_Run`

.. |Section| replace:: :class:`.Section`

.. |Sections| replace:: :class:`.Sections`

.. |Series| replace:: :class:`.Series`

.. |SeriesCollection| replace:: :class:`.SeriesCollection`

.. |SeriesLines| replace:: :class:`~pptx.chart.plot.SeriesLines`

.. |SheetReference| replace:: :class:`~pptx.chart.series.SheetReference`

.. |EffectFormat| replace:: :class:`.EffectFormat`

.. |GlowFormat| replace:: :class:`.GlowFormat`

.. |ReflectionFormat| replace:: :class:`.ReflectionFormat`

.. |SoftEdgeFormat| replace:: :class:`.SoftEdgeFormat`

.. |ShadowFormat| replace:: :class:`.ShadowFormat`

.. |Shape| replace:: :class:`.Shape`

.. |ShapeCollection| replace:: :class:`.ShapeCollection`

.. |Slide| replace:: :class:`.Slide`

.. |Slides| replace:: :class:`.Slides`

.. |SlideLayout| replace:: :class:`.SlideLayout`

.. |SlideLayouts| replace:: :class:`.SlideLayouts`

.. |SlideLayoutPart| replace:: :class:`.SlideLayoutPart`

.. |SlideMaster| replace:: :class:`.SlideMaster`

.. |SlideMasters| replace:: :class:`.SlideMasters`

.. |SlideMasterPart| replace:: :class:`.SlideMasterPart`

.. |SlidePlaceholders| replace:: :class:`.SlidePlaceholders`

.. |SlideShapes| replace:: :class:`.SlideShapes`

.. |SlideTags| replace:: :class:`.SlideTags`

.. |Model3D| replace:: :class:`.Model3D`

.. |SmartArt| replace:: :class:`.SmartArt`

.. |Sound| replace:: :class:`.Sound`

.. |str| replace:: :class:`str`

.. |Table| replace:: :class:`Table`

.. |TagsPart| replace:: :class:`.TagsPart`

.. |TextFrame| replace:: :class:`.TextFrame`

.. |TextFrameRect| replace:: :class:`~pptx.text.text.TextFrameRect`

.. |TickLabels| replace:: :class:`.TickLabels`

.. |Transition| replace:: :class:`.Transition`

.. |Trendline| replace:: :class:`.Trendline`

.. |True| replace:: :class:`True`

.. |TypeError| replace:: :exc:`TypeError`

.. |ValueAxis| replace:: :class:`.ValueAxis`

.. |ValueError| replace:: :exc:`ValueError`

.. |Video| replace:: :class:`.Video`

.. |ViewProps| replace:: :class:`.ViewProps`

.. |WorkbookWriter| replace:: :class:`.WorkbookWriter`

.. |XL_AXIS_POSITION| replace:: :class:`.XL_AXIS_POSITION`

.. |XL_CROSS_BETWEEN| replace:: :class:`.XL_CROSS_BETWEEN`

.. |XL_ERROR_BAR_DIRECTION| replace:: :class:`.XL_ERROR_BAR_DIRECTION`

.. |XL_ERROR_BAR_INCLUDE| replace:: :class:`.XL_ERROR_BAR_INCLUDE`

.. |XL_ERROR_BAR_TYPE| replace:: :class:`.XL_ERROR_BAR_TYPE`

.. |XL_TRENDLINE_TYPE| replace:: :class:`.XL_TRENDLINE_TYPE`

.. |XyChartData| replace:: :class:`.XyChartData`

.. |XyPoints| replace:: :class:`.XyPoints`

.. |XySeries| replace:: :class:`.XySeries`

.. |XySeriesData| replace:: :class:`.XySeriesData`

.. |ZipFileSystem| replace:: :class:`ZipFileSystem`
"""

# List of (type, target) tuples for cross-references that are known to be
# unresolvable and should be silenced under nitpicky (``-n``) mode. These
# fall into two categories:
#
# 1. Internal / undocumented classes and helpers that appear in docstrings
#    and developer notes but have no ``.. autoclass::`` / ``.. automethod::``
#    directive anywhere in the docs tree (e.g. ``XmlPart``, ``ShapeElement``,
#    ``EmbeddedXlsxPart``, private-underscore proxies).
# 2. Cross-references that would resolve under a non-nitpicky build because
#    they match a ``.. class::`` directive in an enum page that does not
#    register the symbol (e.g. ``XL_CHART_TYPE.UNSUPPORTED_CHARTEX`` —
#    the enum page is plain-text, so individual members are not indexed).
#
# Leaving these as warnings produces a wall of noise in ``-n`` mode that
# obscures genuine breakage. Specific targets, not globs, to avoid masking
# future typos.
nitpick_ignore = [
    ("py:attr", "APPEAR"),
    ("py:attr", "BaseShape.effective_height"),
    ("py:attr", "BaseShape.effective_left"),
    ("py:attr", "BaseShape.effective_top"),
    ("py:attr", "BaseShape.effective_width"),
    ("py:attr", "Chart.chart_style"),
    ("py:attr", "Chart.data_table"),
    ("py:attr", "Chart.has_secondary_value_axis"),
    ("py:attr", "Chart.primary_value_axis"),
    ("py:attr", "Chart.secondary_value_axis"),
    ("py:attr", "Chart.value_axis"),
    ("py:attr", "Chart.workbook"),
    ("py:attr", "DataLabel.number_format"),
    ("py:attr", "DataLabel.number_format_is_linked"),
    ("py:attr", "FADE_IN"),
    ("py:attr", "FADE_OUT"),
    ("py:attr", "FLY_IN"),
    ("py:attr", "Font.highlight_color"),
    ("py:attr", "GraphicFrame.chart"),
    ("py:attr", "GraphicFrame.chart_type"),
    ("py:attr", "GraphicFrame.chartex_type"),
    ("py:attr", "GraphicFrame.has_chartex"),
    ("py:attr", "GraphicFrame.model_3d"),
    ("py:attr", "MOVING_AVG"),
    ("py:attr", "MSO_ANIMATION_TRIGGER.AFTER_PREVIOUS"),
    ("py:attr", "MSO_AUTO_SIZE.NONE"),
    ("py:attr", "MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE"),
    ("py:attr", "MSO_SHAPE_TYPE.CHART"),
    ("py:attr", "MSO_SHAPE_TYPE.IGX_GRAPHIC"),
    ("py:attr", "Movie.start_condition"),
    ("py:attr", "Movie.start_time"),
    ("py:attr", "ON_CLICK"),
    ("py:attr", "POLYNOMIAL"),
    ("py:attr", "PP_TRANSITION_TYPE.MORPH"),
    ("py:attr", "PP_TRANSITION_TYPE.NONE"),
    ("py:attr", "PULSE"),
    ("py:attr", "PlaceholderFormat.type"),
    ("py:attr", "Point.data_label"),
    ("py:attr", "Presentation.first_slide_num"),
    ("py:attr", "Presentation.view_props"),
    ("py:attr", "Shape.rotation"),
    ("py:attr", "Slide.background"),
    ("py:attr", "Slide.follow_master_background"),
    ("py:attr", "Slide.shapes"),
    ("py:attr", "Slide.show_master_shapes"),
    ("py:attr", "SlideMaster.header_footer"),
    ("py:attr", "SlideMaster.theme_colors"),
    ("py:attr", "Table.style_id"),
    ("py:attr", "TextFrame.auto_size"),
    ("py:attr", "TextFrame.word_wrap"),
    ("py:attr", "ViewProps.element"),
    ("py:attr", "XL_CHART_TYPE.THREE_D_PIE"),
    ("py:attr", "XL_CHART_TYPE.UNSUPPORTED_CHARTEX"),
    ("py:attr", "XL_DISPLAY_BLANKS_AS.ZERO"),
    ("py:attr", "XL_ERROR_BAR_TYPE.FIXED_VALUE"),
    ("py:attr", "_Background.fill"),
    ("py:attr", "_BaseAxis.visible"),
    ("py:attr", "_BaseSlidePlaceholder.shape_type"),
    ("py:attr", "__iter__"),
    ("py:attr", "chart"),
    ("py:attr", "has_text_frame"),
    ("py:attr", "idx"),
    ("py:attr", "shape_type"),
    ("py:class", "BaseOxmlElement"),
    ("py:class", "BaseShape"),
    ("py:class", "BaseSlidePart"),
    ("py:class", "CT_PresetGeometry2D"),
    ("py:class", "CategoryChartData"),
    ("py:class", "ChartData"),
    ("py:class", "ChartData.xlsx_blob"),
    ("py:class", "ChartDrawingPart"),
    ("py:class", "ChartExPart"),
    ("py:class", "ChartPart"),
    ("py:class", "EmbeddedXlsxPart"),
    ("py:class", "ExtendedPropertiesPart"),
    ("py:class", "GraphicFrame"),
    ("py:class", "ImagePart"),
    ("py:class", "MSO_ANIMATION_TRIGGER"),
    ("py:class", "MSO_ANIMATION_TYPE"),
    ("py:class", "MSO_AUTO_SHAPE_TYPE"),
    ("py:class", "MSO_CONNECTOR_TYPE"),
    ("py:class", "MSO_SHAPE"),
    ("py:class", "MSO_TEXT_STRIKE_TYPE"),
    ("py:class", "MSO_THEME_COLOR"),
    ("py:class", "MediaPart"),
    ("py:class", "PP_AUTO_NUMBER_SCHEME"),
    ("py:class", "PP_TRANSITION_SIDE_DIRECTION"),
    ("py:class", "PP_TRANSITION_SPEED"),
    ("py:class", "PP_TRANSITION_TYPE"),
    ("py:class", "PROG_ID"),
    ("py:class", "Part"),
    ("py:class", "ProvidesPart"),
    ("py:class", "ShapeElement"),
    ("py:class", "ThemeStyleRefs"),
    ("py:class", "ViewPropsPart"),
    ("py:class", "WorkbookReader"),
    ("py:class", "WorkbookUpdater"),
    ("py:class", "XL_CHART_TYPE"),
    ("py:class", "XmlPart"),
    ("py:class", "ZipDateTime"),
    ("py:class", "_Background"),
    ("py:class", "_BaseSlidePlaceholder"),
    ("py:class", "datetime.datetime"),
    ("py:class", "pptx.enum.chart.XL_CHART_TYPE"),
    ("py:class", "pptx.enum.chart.XL_TRENDLINE_TYPE"),
    ("py:class", "pptx.enum.presentation.PP_VIEW_TYPE"),
    ("py:class", "pptx.enum.shapes.MSO_AUTO_SHAPE_TYPE"),
    ("py:class", "pptx.enum.shapes.MSO_SHAPE_TYPE"),
    ("py:class", "pptx.enum.text.MSO_AUTO_SIZE"),
    ("py:class", "pptx.enum.text.PP_AUTO_NUMBER_SCHEME"),
    ("py:class", "pptx.opc.package.Part"),
    ("py:class", "pptx.opc.package.PartFactory"),
    ("py:class", "pptx.opc.package.PartRelationshipCloner"),
    ("py:class", "pptx.oxml.shapes.graphfrm.CT_DgmRelIds"),
    ("py:class", "pptx.oxml.shapes.graphfrm.CT_GraphicalObjectData"),
    ("py:class", "pptx.shapes.base._CustomPropsDict"),
    ("py:class", "pptx.shapes.graphfrm._OleFormat"),
    ("py:class", "pptx.shared.ParentedElementProxy"),
    ("py:class", "pptx.slide._BaseSlide"),
    ("py:class", "pptx.slide._FollowMasterBackground"),
    ("py:class", "zipfile.ZipFile"),
    ("py:data", "pptx.content_type_to_part_class_map"),
    ("py:data", "pptx.oxml.ns._nsmap"),
    ("py:data", "pptx.spec.GRAPHIC_DATA_URI_MODEL_3D"),
    ("py:data", "pptx.spec.GRAPHIC_DATA_URI_SMART_ART"),
    ("py:func", "Presentation"),
    ("py:func", "SlideShapeFactory"),
    ("py:func", "_row_col_to_a1"),
    ("py:func", "clone_embedded_xlsx"),
    ("py:func", "parse_a1_cell"),
    ("py:func", "pptx.oxml.timing.iter_main_sequence_effects"),
    ("py:func", "update_embedded_xlsx_cell"),
    ("py:meth", "ActionSetting.set_sound"),
    ("py:meth", "Chart.add_plot"),
    ("py:meth", "Chart.replace_data"),
    ("py:meth", "Chart.replace_data_preserve_formulas"),
    ("py:meth", "Chart.set_axis_title"),
    ("py:meth", "Chart.set_title"),
    ("py:meth", "Chart.update_cached_values"),
    ("py:meth", "ChartWorkbook.update_from_xlsx_blob"),
    ("py:meth", "ColorFormat.to_rgb"),
    ("py:meth", "GroupShape.duplicate"),
    ("py:meth", "Presentation.merge"),
    ("py:meth", "Presentation.save"),
    ("py:meth", "Shapes.add_chart"),
    ("py:meth", "Slide.find_shapes_by_xpath"),
    ("py:meth", "SlideShapes.add_chart"),
    ("py:meth", "SlideShapes.add_movie"),
    ("py:meth", "SlideShapes.add_picture"),
    ("py:meth", "SlideShapes.clear"),
    ("py:meth", "SlideShapes.descendants"),
    ("py:meth", "Slides.add_slide"),
    ("py:meth", "Slides.add_slide_from_external"),
    ("py:meth", "Slides.delete"),
    ("py:meth", "Slides.duplicate"),
    ("py:meth", "Slides.move_slide"),
    ("py:meth", "Table.iter_cells"),
    ("py:meth", "TextFrame.autofit_text"),
    ("py:meth", "TextFrame.fit_text"),
    ("py:meth", "TextFrame.replace_text"),
    ("py:meth", "_BaseSlidePlaceholder.insert_chart"),
    ("py:meth", "_BaseSlidePlaceholder.insert_picture"),
    ("py:meth", "_BaseSlidePlaceholder.insert_table"),
    ("py:meth", "_CustomPropsDict.clear"),
    ("py:meth", "_CustomPropsDict.get"),
    ("py:meth", "add_slide"),
    ("py:meth", "insert_chart"),
    ("py:meth", "insert_picture"),
    ("py:meth", "insert_table"),
    ("py:meth", "list.clear"),
    ("py:meth", "merge"),
    ("py:mod", "pptx.oxml"),
    ("py:mod", "pptx.oxml.ns"),
    # -- Round 2: additional long-tail targets (single-occurrence and low-count
    # undocumented proxies, parenthesised ``:meth:`` call syntax in analysis
    # notes, and third-party targets like ``lxml`` / ``io.BytesIO``). --
    ("py:attr", "AFTER_PREVIOUS"),
    ("py:attr", "ActionSetting.screen_tip"),
    ("py:attr", "ActionSetting.target_slide"),
    ("py:attr", "BaseShape.click_action"),
    ("py:attr", "BaseShape.hover_action"),
    ("py:attr", "BaseShape.is_hidden"),
    ("py:attr", "BaseShape.math_equation_xml"),
    ("py:attr", "BaseShape.text_frame"),
    ("py:attr", "BaseSlide.shapes"),
    ("py:attr", "CT.OFC_CHART_EX"),
    ("py:attr", "CategoryAxis.label_align"),
    ("py:attr", "CategoryAxis.tick_label_skip"),
    ("py:attr", "CategoryAxis.tick_mark_skip"),
    ("py:attr", "Chart.category_axis"),
    ("py:attr", "Chart.chart_type"),
    ("py:attr", "Chart.display_blanks_as"),
    ("py:attr", "Chart.has_data_table"),
    ("py:attr", "Chart.series_in_rows"),
    ("py:attr", "Chart.workbook = ..."),
    ("py:attr", "ColorFormat.rgb"),
    ("py:attr", "ColorFormat.theme_color"),
    ("py:attr", "DataLabel.text_frame"),
    ("py:attr", "DataLabel.text_from_cells"),
    ("py:attr", "DataLabels.number_format"),
    ("py:attr", "DataLabels.text_frame"),
    ("py:attr", "EXPONENTIAL"),
    ("py:attr", "Font.size"),
    ("py:attr", "Font.strikethrough"),
    ("py:attr", "Font.use_theme_hyperlink_color"),
    ("py:attr", "GraphicFrame.has_chart"),
    ("py:attr", "GraphicFrame.has_model_3d"),
    ("py:attr", "GraphicFrame.model_3d_xml"),
    ("py:attr", "GraphicFrame.shape_type"),
    ("py:attr", "GraphicFrame.smart_art"),
    ("py:attr", "GroupShape.shapes"),
    ("py:attr", "Image.blob"),
    ("py:attr", "ImagePart.blob"),
    ("py:attr", "LINEAR"),
    ("py:attr", "LOGARITHMIC"),
    ("py:attr", "MSO_ANIMATION_TYPE.NONE"),
    ("py:attr", "MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT"),
    ("py:attr", "PERCENT"),
    ("py:attr", "POWER"),
    ("py:attr", "PP_TRANSITION_SPEED.FAST"),
    ("py:attr", "PP_VIEW_TYPE.NORMAL"),
    ("py:attr", "Part.blob"),
    ("py:attr", "Picture.image"),
    ("py:attr", "PlaceholderFormat.idx"),
    ("py:attr", "Presentation.core_properties"),
    ("py:attr", "Presentation.extended_properties"),
    ("py:attr", "STDEV"),
    ("py:attr", "Shape.alt_text"),
    ("py:attr", "Slide.background.fill"),
    ("py:attr", "Slide.shape_tree_flat"),
    ("py:attr", "SlideLayout.background"),
    ("py:attr", "SlideLayout.name"),
    ("py:attr", "SlideLayout.shapes"),
    ("py:attr", "SlideLayout.slide_layout_type"),
    ("py:attr", "SlideMaster.shapes"),
    ("py:attr", "Table.first_row"),
    ("py:attr", "Table.horz_banding"),
    ("py:attr", "TickLabels.rotation"),
    ("py:attr", "Transition.advance_after_time"),
    ("py:attr", "XL_CHART_TYPE.THREE_D_PIE_EXPLODED"),
    ("py:attr", "XL_DISPLAY_BLANKS_AS.GAPS"),
    ("py:attr", "XL_ERROR_BAR_INCLUDE.BOTH"),
    ("py:attr", "XL_TRENDLINE_TYPE.LINEAR"),
    ("py:attr", "XL_TRENDLINE_TYPE.MOVING_AVG"),
    ("py:attr", "XL_TRENDLINE_TYPE.POLYNOMIAL"),
    ("py:attr", "_InheritsPlaceholderFormat.placeholder_format"),
    ("py:attr", "_ShapeCollection.placeholders"),
    ("py:attr", "core_properties"),
    ("py:attr", "custom_properties"),
    ("py:attr", "error_bars"),
    ("py:attr", "format"),
    ("py:attr", "gap_width"),
    ("py:attr", "has_math_equation"),
    ("py:attr", "has_secondary_value_axis"),
    ("py:attr", "other_cell.merge(cell)"),
    ("py:attr", "partname_template"),
    ("py:attr", "points"),
    ("py:attr", "pptx.chart.legend.Legend.hidden_entries"),
    ("py:attr", "pptx.opc.package.Part.blob"),
    ("py:attr", "pptx.oxml.shapes.graphfrm.CT_GraphicalObjectData.dgm_relIds"),
    ("py:attr", "pptx.oxml.shapes.graphfrm.CT_GraphicalObjectData.model_3d"),
    ("py:attr", "pptx.parts.chart.ChartWorkbook.xlsx_part"),
    ("py:attr", "pptx.presentation.slide_masters"),
    ("py:attr", "pptx.shapes.graphfrm.GraphicFrame.shape_type"),
    ("py:attr", "slides"),
    ("py:attr", "transition.type"),
    ("py:class", "ActionSetting"),
    ("py:class", "CT_Background"),
    ("py:class", "CT_Placeholder"),
    ("py:class", "CT_Section"),
    ("py:class", "CT_Shape"),
    ("py:class", "CT_SlideIdList"),
    ("py:class", "CT_SlideLayoutIdList"),
    ("py:class", "CT_TableCell"),
    ("py:class", "CT_ViewProperties"),
    ("py:class", "ChartWorkbook"),
    ("py:class", "Choice"),
    ("py:class", "DataLabels"),
    ("py:class", "DescribePoint"),
    ("py:class", "ElementProxy"),
    ("py:class", "FillFormat"),
    ("py:class", "Inches"),
    ("py:class", "LayoutShapes"),
    ("py:class", "MSO_FILL_TYPE"),
    ("py:class", "MSO_SHAPE_TYPE"),
    ("py:class", "MSO_TEXT_UNDERLINE_TYPE"),
    ("py:class", "MSO_VERTICAL_ANCHOR"),
    ("py:class", "MasterShapes"),
    ("py:class", "NotesMaster"),
    ("py:class", "NotesSlidePlaceholder"),
    ("py:class", "OneAndOnlyOne"),
    ("py:class", "OptionalAttribute"),
    ("py:class", "PP_AUTO_NUMBER"),
    ("py:class", "PP_PARAGRAPH_ALIGNMENT"),
    ("py:class", "PP_PLACEHOLDER"),
    ("py:class", "PP_VIEW_TYPE"),
    ("py:class", "PackURI"),
    ("py:class", "Package"),
    ("py:class", "PackageWriter"),
    ("py:class", "PartElementProxy"),
    ("py:class", "RequiredAttribute"),
    ("py:class", "ST_TransitionMorphOption"),
    ("py:class", "Sections"),
    ("py:class", "ShapeAnimation"),
    ("py:class", "Slide._EffectiveBackground"),
    ("py:class", "Slide.shapes"),
    ("py:class", "SlideShapes"),
    ("py:class", "Slides"),
    ("py:class", "TextFrame"),
    ("py:class", "XL_ERROR_BAR_DIRECTION"),
    ("py:class", "XyPlot"),
    ("py:class", "XySeries"),
    ("py:class", "ZeroOrMore"),
    ("py:class", "ZeroOrOne"),
    ("py:class", "ZeroOrOneChoice"),
    ("py:class", "_BaseSeries"),
    ("py:class", "_Fill"),
    ("py:class", "io.BytesIO"),
    ("py:class", "pptx.chart.exchart.ExChart"),
    ("py:class", "pptx.chart.plot.PlotArea"),
    ("py:class", "pptx.chart.series.Series.name"),
    ("py:class", "pptx.chart.xlsx.CategoryWorkbookWriter"),
    ("py:class", "pptx.chart.xmlwriter._BarPlotFragmentBuilder"),
    ("py:class", "pptx.chart.xmlwriter._CategorySeriesXmlWriter"),
    ("py:class", "pptx.chart.xmlwriter._LinePlotFragmentBuilder"),
    ("py:class", "pptx.chart.xmlwriter._PlotFragmentBuilder"),
    ("py:class", "pptx.enum.chart.XL_TICK_LABEL_ALIGNMENT"),
    ("py:class", "pptx.enum.dml.MSO_LINE"),
    ("py:class", "pptx.enum.dml.MSO_LINE_END_LENGTH"),
    ("py:class", "pptx.enum.dml.MSO_LINE_END_TYPE"),
    ("py:class", "pptx.enum.dml.MSO_LINE_END_WIDTH"),
    ("py:class", "pptx.enum.dml.MSO_THEME_COLOR"),
    ("py:class", "pptx.enum.lang.MSO_LANGUAGE_ID"),
    ("py:class", "pptx.enum.shapes.PP_MEDIA_TYPE"),
    ("py:class", "pptx.enum.shapes.PROG_ID"),
    ("py:class", "pptx.enum.text.MSO_VERTICAL_ANCHOR"),
    ("py:class", "pptx.enum.transition.PP_TRANSITION_SIDE_DIRECTION"),
    ("py:class", "pptx.enum.transition.PP_TRANSITION_SPEED"),
    ("py:class", "pptx.enum.transition.PP_TRANSITION_TYPE"),
    ("py:class", "pptx.opc.package.XmlPart"),
    ("py:class", "pptx.oxml.chart.axis.CT_ChartLines"),
    ("py:class", "pptx.oxml.shapes.graphfrm.CT_Model3D"),
    ("py:class", "pptx.oxml.xmlchemy.Choice"),
    ("py:class", "pptx.parts.image.ImagePart"),
    ("py:class", "pptx.shapes.shapetree.UserShapes"),
    ("py:class", "pptx.shapes.shapetree._BaseGroupShapes"),
    ("py:class", "pptx.shared.ElementProxy"),
    ("py:class", "pptx.slide.ShapeAnimation"),
    ("py:const", "pptx.opc.constants.CONTENT_TYPE.OFC_CHART_EX"),
    ("py:const", "pptx.spec.GRAPHIC_DATA_URI_CHARTEX"),
    ("py:data", "pptx.oxml.ns.nsmap"),
    ("py:data", "pptx.oxml.oxml_parser"),
    ("py:func", "iter_main_sequence_effects"),
    ("py:func", "len"),
    ("py:func", "pptx.chart.chart.update_embedded_xlsx_cell"),
    ("py:func", "pptx.opc._crypto.is_rms_protected_stream"),
    ("py:func", "pptx.oxml.ns.qn"),
    ("py:func", "pptx.oxml.parse_xml"),
    ("py:func", "pptx.oxml.timing.first_spTgt_spid"),
    ("py:func", "pptx.parts.embeddedpackage.clone_embedded_xlsx"),
    ("py:meth", "ActionSetting.remove_sound"),
    ("py:meth", "Audio.ext"),
    ("py:meth", "Chart.add_user_shape"),
    ("py:meth", "Chart.apply_template"),
    ("py:meth", "Chart.workbook"),
    ("py:meth", "ChartData.add_series"),
    ("py:meth", "ChartDrawingPart.iter_anchor_elements"),
    ("py:meth", "ChartDrawingPart.new"),
    ("py:meth", "ChartPart.clone_from"),
    ("py:meth", "ChartPart.new"),
    ("py:meth", "CommentAuthors.add_author"),
    ("py:meth", "CommentAuthors.get_or_add"),
    ("py:meth", "Comments.add_comment"),
    ("py:meth", "Font.clear_highlight_color"),
    ("py:meth", "GroupShape.ungroup"),
    ("py:meth", "Movie.replace_media"),
    ("py:meth", "OpcPackage.iter_parts"),
    ("py:meth", "OpcPackage.save"),
    ("py:meth", "Presentation.embed_font"),
    ("py:meth", "Presentation.strip_slides"),
    ("py:meth", "Section.add_slide"),
    ("py:meth", "Sections.add_section"),
    ("py:meth", "Sections.remove"),
    ("py:meth", "Series.delete"),
    ("py:meth", "Shape.delete"),
    ("py:meth", "Slide.clear_shapes"),
    ("py:meth", "Slide.shapes.add_table"),
    ("py:meth", "SlideLayoutPart.clone_from"),
    ("py:meth", "SlideLayouts.get_by_name"),
    ("py:meth", "SlideLayouts.get_by_type"),
    ("py:meth", "SlidePart.get_or_add_image_part"),
    ("py:meth", "SlideShapes.add_movie_link"),
    ("py:meth", "SlideShapes.add_table"),
    ("py:meth", "SlideShapes.add_textbox"),
    ("py:meth", "SlideShapes.find_all_by_name"),
    ("py:meth", "SlideShapes.get_by_name"),
    ("py:meth", "Video.ext"),
    ("py:meth", "Video.from_blob"),
    ("py:meth", "Video.from_path_or_file_like"),
    ("py:meth", "XmlPart.drop_rel"),
    ("py:meth", "_Paragraph.replace_text"),
    ("py:meth", "_get_or_add_transition"),
    ("py:meth", "add_chart"),
    ("py:meth", "add_slide(slide_layout)"),
    ("py:meth", "add_slide_from_external(source_slide, slide_layout)"),
    ("py:meth", "close"),
    ("py:meth", "delete(slide)"),
    ("py:meth", "duplicate(index=...)"),
    ("py:meth", "duplicate(slide, index=None)"),
    ("py:meth", "embed_font"),
    ("py:meth", "lxml.etree._Element.xpath"),
    ("py:meth", "move_slide"),
    ("py:meth", "move_slide(slide, new_idx)"),
    ("py:meth", "pptx.chart.legend.Legend.exclude_entry"),
    ("py:meth", "pptx.chart.legend.Legend.include_entry"),
    ("py:meth", "pptx.opc.package.Part.related_part"),
    ("py:meth", "pptx.oxml.presentation.CT_SlideIdList.add_sldId"),
    ("py:meth", "pptx.package._ImageParts.get_or_add_image_part"),
    ("py:meth", "pptx.parts.image.Image.from_file"),
    ("py:meth", "pptx.shapes.shapetree.BaseGroupShapes.build_freeform"),
    ("py:meth", "pptx.shapes.shapetree._BaseGroupShapes._recalculate_extents"),
    ("py:meth", "shapes.add_chart"),
    ("py:mod", "lxml"),
    ("py:mod", "pptx"),
    ("py:mod", "pptx.__init__"),
    ("py:mod", "pptx.chart"),
    ("py:mod", "pptx.chart.xlsx"),
    ("py:mod", "pptx.opc.constants"),
    ("py:mod", "pptx.oxml.shapes"),
    ("py:mod", "pptx.shapes"),
    ("py:mod", "pptx.shapes.model3d"),
    ("py:mod", "pptx.slide"),
    ("py:mod", "util"),
]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [".build"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []


# -- Options for HTML output ------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "source_repository": "https://github.com/loadfix/python-pptx/",
    "source_branch": "master",
    "source_directory": "docs/",
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# Furo supplies its own sidebar out of the box; keep defaults.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = "python-pptxdoc"


# -- Options for LaTeX output -----------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author,
#  documentclass [howto/manual]).
latex_documents = [
    (
        "index",
        "python-pptx.tex",
        u"python-pptx Documentation",
        u"Steve Canny",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output -----------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ("index", "python-pptx", u"python-pptx Documentation", [u"Steve Canny"], 1)
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output ---------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "python-pptx",
        u"python-pptx Documentation",
        u"Steve Canny",
        "python-pptx",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'


# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/': None}
