name: ci

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install test dependencies
        run: |
          pip install .
          pip install -r requirements-test.txt
      - name: Test with pytest
        run: pytest --cov=pptx --cov-report term-missing tests
      - name: Acceptance tests with behave
        run: behave --stop
